# Generated by Django 6.0 on 2025-12-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='id_profile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id_proyect',
            new_name='proyect',
        ),
    ]
