# Generated by Django 6.0 on 2025-12-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_project_done_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='proyect',
            new_name='project',
        ),
    ]
